resource "aws_cloudwatch_dashboard" "main" {
  dashboard_name = "my-dashboard"

  dashboard_body = <<EOF
 {  
    "widgets":[  
       {  
          "type":"metric",
          "x":0,
          "y":0,
          "width":24,
          "height":3,
          "styles":"undefined",
          "properties":{  
             "view":"singleValue",
             "metrics":[  
                [  
                   "AWS/EC2",
                   "CPUUtilization",
                   "InstanceId",
                   "i-0e079d3ea4b18b200"
                ],
                [  
                   ".",
                   "NetworkIn",
                   ".",
                   "."
                ],
                [  
                   ".",
                   "NetworkOut",
                   ".",
                   "."
                ],
                [  
                   ".",
                   "StatusCheckFailed",
                   ".",
                   "."
                ],
                [  
                   ".",
                   "StatusCheckFailed_System",
                   ".",
                   "."
                ]
             ],
             "region":"us-east-1"
          }
       },
       {  
          "type":"metric",
          "x":0,
          "y":3,
          "width":12,
          "height":3,
          "styles":"undefined",
          "properties":{  
             "view":"singleValue",
             "metrics":[  
                [  
                   "AWS/Lambda",
                   "Errors"
                ],
                [  
                   ".",
                   "Invocations"
                ]
             ],
             "region":"us-east-1"
          }
       },
       {  
          "type":"metric",
          "x":12,
          "y":3,
          "width":6,
          "height":6,
          "styles":"undefined",
          "properties":{  
             "view":"timeSeries",
             "stacked":false,
             "metrics":[  
                [  
                   "AWS/Lambda",
                   "Errors"
                ],
                [  
                   ".",
                   "Invocations"
                ]
             ],
             "region":"us-east-1"
          }
       }
    ]
 }
 EOF
}
